### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be greater than origin when using portal

### ISSUE THREAD

**Issue by B-Knight49** [AcmeProject/WildernessTp#64]
https://www.spigotmc.org/threads/wilderness-tp.145440/page-29#post-3696748

I linked my log a few messages below that one. I couldn't see anything that might cause problems. Unfortunately, this is still an issue so opening this. 

In the meantime - since it seems you've been inactive or busy - I'm going to try edit the source myself and see if I can narrow it down in order to fix it. If I find the problem, I'll update the issue here and explain what it was. 

Wild version 2.15-a6aebd3
Paper #103 
MC 1.15.2

**Comment by RoboMWM** [comment]
> since it seems you've been inactive or busy

No, it's just that I don't look for bugs on spigotmc. That's where I answer questions. By the time I'm at an IDE I'm looking solely at github for the most part.

**Comment by B-Knight49** [comment]
Ah gotcha, my bad. It's just because you hadn't responded to the discussion is all. I should've opened an issue here earlier to be honest, so that's my fault.

**Comment by RoboMWM** [comment]
Gonna need to see your config.

**Comment by B-Knight49** [comment]
They're all Gists, not downloads. Added the other two just to be certain and rule out everything. 

[Config.yml](https://gist.github.com/B-Knight49/1028cf062fdfbc34cb02deb64cc007aa)
[Messages.yml](https://gist.github.com/B-Knight49/1c2afc9f70c683729667f330759baa31)
[Portals.yml](https://gist.github.com/B-Knight49/dd316d959fef9cc8d9402147f7494817)

**Comment by RoboMWM** [comment]
Yea, using 71a8cfd will help get a specific line.

**Comment by B-Knight49** [comment]
Sorry, can you do me a favour and send through a built .jar? Whenever I build it, my plugin manager throws errors and can't seem to identify it. It keeps complaining about the plugin.yml but I've checked repeatedly and it's all fine.

**Comment by RoboMWM** [comment]
https://ci.appveyor.com/api/buildjobs/61sja4vrx9ha1lsk/artifacts/target%2FWildTP.jar

**Comment by B-Knight49** [comment]
Cheers. Here's the full stacktrace:

https://mcpaste.io/432ad8f749c26584

**Comment by RoboMWM** [comment]
Ok better, can you enable debug mode and paste output?

**Comment by B-Knight49** [comment]
That is debug mode and that is the output...

**Comment by RoboMWM** [comment]
Oh ok. I saw debug messages for printing the world border but doesn't seem that has been fired here. What's the border of `world`? e.g. what are the outputs of the border `get` and `center` commands.

**Comment by B-Knight49** [comment]
Added my own quick debug lines to see if it'd do anything. 
wc, who and way is below:

> [19:14:12 WARN]: player = CraftPlayer{name=BKnight_}
> [19:14:12 WARN]: worldconfig = net.poweredbyhate.wildtp.WorldConfig@48a8f091
> [19:14:12 WARN]: direction = null

Worldborder get is 60000000. Center is -784.37, 500172.56
WorldBorder is 60K x 60K. 
X = -30,000 to 30,000
Z = 470,000 to 530,000

Lemme know if you need anything else.

**Comment by RoboMWM** [comment]
found a typo in his worldborder logic for vanilla worldborders. Gonna also add debugging info to that. Either way though I'm gonna guess the typo will fix this (it had to do with the Z value which yours is very large compared to the X value).

**Comment by B-Knight49** [comment]
> for vanilla worldborders.

We don't use a vanilla one though, we use the plugin [WorldBorder](https://www.spigotmc.org/resources/worldborder.60905/)?

**Comment by RoboMWM** [comment]
I was trying to respond to this and mysteriously somehow I can't access or ping any of GitHub.com's servers from just my home internet so that's wonderful, and I have no idea why it's happening. Anyways...

**Comment by RoboMWM** [comment]
Uhm... ok, so it affects only the WorldBorder plugin (vanilla worldborder had a different issue). If you're using the worldborder plugin then /worldborder get and etc. I don't think would've worked... also, if you're using the WorldBorder plugin you should've had debug messages printing out said border...

That being said the minXY includes both X and Z so your config doesn't match your world border. Hmm.

**Comment by RoboMWM** [comment]
idk why I accepted this PR, I thought the code we wrote was semi obfuscated but this is just big oof

**Comment by B-Knight49** [comment]
> idk why I accepted this PR, I thought the code we wrote was semi obfuscated but this is just big oof

Not sure what you mean. The code is definitely not obfuscated and thank fuck it's not. Please, please do not obfuscate your code. 

Regardless, if you think you've fixed it, I appreciate it.

**Comment by RoboMWM** [comment]
a couple thousand lines of changes https://github.com/AcmeProject/WildernessTp/pull/44/files

**Comment by B-Knight49** [comment]
Okay - has Github broken? hahahahaha

**Comment by RoboMWM** [comment]
Ok, yea it's also called when the WorldConfig is generated (which I guess is during onEnable) so yea that should fix it.

Yea takes a while to load that enormous diff lol.

**Comment by B-Knight49** [comment]
Sorry for the delay;

That didn't fix it. I've built your recent commit and I still get the same error as before. 
On another note, I needed to add a description to your plugin.yml else my plugin manager refuses to load it. That was annoying lol.

**Comment by RoboMWM** [comment]
Have a word with @LaxWasHere
